<h1 style='color:blue;' align='center'>KFold Cross Validation Python Tutorial</h2>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
digits = load_iris()
print(digits)

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

**Logistic Regression**

In [41]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9333333333333333

**SVM**

In [42]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9555555555555556

**Random Forest**

In [43]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9555555555555556

<h2 style='color:purple'>KFold cross validation</h2>

**Basic example**

In [44]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5,shuffle=True)
kf

KFold(n_splits=5, random_state=None, shuffle=True)

In [38]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[0 1 3 5 6 7 8] [2 4]
[0 1 2 3 4 6 8] [5 7]
[2 3 4 5 6 7 8] [0 1]
[0 1 2 3 4 5 7] [6 8]
[0 1 2 4 5 6 7 8] [3]


**Use KFold for our digits example**

In [45]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [46]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [47]:
scores_logistic

[0.96, 0.96, 0.94]

In [48]:
scores_svm

[0.98, 0.98, 0.96]

In [49]:
scores_rf

[0.98, 0.94, 0.98]

<h2 style='color:purple'>cross_val_score function</h2>

In [50]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [51]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.96, 0.96, 0.94])

**svm model performance using cross_val_score**

In [52]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.98, 0.98, 0.96])

**random forest performance using cross_val_score**

In [53]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.98, 0.94, 0.94])

cross_val_score uses stratifield kfold by default

<h2 style='color:purple'>Parameter tunning using k fold cross validation</h2>

In [54]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.9533333333333334

In [55]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9666666666666666

In [19]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9465704531346988

In [20]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9448975791433891

Here we used cross_val_score to
fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result. 

<h2 style='color:purple'>Exercise</h2>

Use iris flower dataset from sklearn library and use cross_val_score against following
models to measure the performance of each. In the end figure out the model with best performance,
1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest